spin_manifest_version = 2

[application]
authors = ["karthik2804 <karthik.ganeshram@fermyon.com>"]
description = ""
name = "simple-test"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "simple-test"

[component.simple-test]
source = "target/simple-test.wasm"
exclude_files = ["**/node_modules"]
[component.simple-test.build]
command = "npm run build"
watch = ["src/**/*.ts", "package.json"]